graph TD;
A[Seller/Brand sends legal notice to our legal team];
B[Legal team vets seller documentation];
C[Legal team escalates case to catalog team if documentation is proper];
D[Legal team reverts complaint to seller if documentation is incomplete];
E[Catalog team fetches seller and product data against infringed brand and updates sheet];
F[Catalog team updates sheet to notify sellers];
G[Engagement team notifies sellers daily by following the sheet];
H[Legal team shares verdict if seller has documentation to share];
I[Seller's products taken down if documentation is not provided within 14 days];
J[Catalog team removes assortment after 15 days if no documentation is shared];
K[Removal is held if documentation is shared until legal team's verdict];
L[Legal team notifies brand/seller accordingly];

A --> B;
B --> |Documentation proper| C;
B --> |Documentation incomplete| D;
C --> E;
D --> E;
E --> F;
F --> G;
H --> L;
I --> J;
J --> |No documentation shared| L;
K --> L;
